# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dia_hinge_joint.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_dia_hinge_joint(object):
    def setupUi(self, dia_hinge_joint):
        if dia_hinge_joint.objectName():
            dia_hinge_joint.setObjectName(u"dia_hinge_joint")
        dia_hinge_joint.resize(600, 400)
        self.buttonBox = QDialogButtonBox(dia_hinge_joint)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(30, 370, 341, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.node_1_Box = QComboBox(dia_hinge_joint)
        self.node_1_Box.setObjectName(u"node_1_Box")
        self.node_1_Box.setGeometry(QRect(90, 20, 101, 22))
        font = QFont()
        font.setPointSize(10)
        self.node_1_Box.setFont(font)
        self.node_1_label = QLabel(dia_hinge_joint)
        self.node_1_label.setObjectName(u"node_1_label")
        self.node_1_label.setGeometry(QRect(90, 0, 91, 21))
        font1 = QFont()
        font1.setPointSize(12)
        self.node_1_label.setFont(font1)
        self.node_2_Box = QComboBox(dia_hinge_joint)
        self.node_2_Box.setObjectName(u"node_2_Box")
        self.node_2_Box.setGeometry(QRect(380, 30, 121, 22))
        self.node_2_Box.setFont(font)
        self.node_2_label = QLabel(dia_hinge_joint)
        self.node_2_label.setObjectName(u"node_2_label")
        self.node_2_label.setGeometry(QRect(380, 10, 91, 21))
        self.node_2_label.setFont(font1)
        self.node1_pos_x = QLineEdit(dia_hinge_joint)
        self.node1_pos_x.setObjectName(u"node1_pos_x")
        self.node1_pos_x.setGeometry(QRect(20, 90, 81, 20))
        self.node1_pos_x.setFont(font)
        self.node1_posx_lab = QLabel(dia_hinge_joint)
        self.node1_posx_lab.setObjectName(u"node1_posx_lab")
        self.node1_posx_lab.setGeometry(QRect(20, 70, 81, 21))
        font2 = QFont()
        font2.setPointSize(11)
        self.node1_posx_lab.setFont(font2)
        self.node1_pos_y = QLineEdit(dia_hinge_joint)
        self.node1_pos_y.setObjectName(u"node1_pos_y")
        self.node1_pos_y.setGeometry(QRect(110, 90, 81, 20))
        self.node1_pos_y.setFont(font)
        self.node1_posy_lab = QLabel(dia_hinge_joint)
        self.node1_posy_lab.setObjectName(u"node1_posy_lab")
        self.node1_posy_lab.setGeometry(QRect(110, 70, 81, 21))
        self.node1_posy_lab.setFont(font2)
        self.node1_pos_z = QLineEdit(dia_hinge_joint)
        self.node1_pos_z.setObjectName(u"node1_pos_z")
        self.node1_pos_z.setGeometry(QRect(200, 90, 81, 20))
        self.node1_pos_z.setFont(font)
        self.node1_posz_lab = QLabel(dia_hinge_joint)
        self.node1_posz_lab.setObjectName(u"node1_posz_lab")
        self.node1_posz_lab.setGeometry(QRect(200, 70, 81, 21))
        self.node1_posz_lab.setFont(font2)
        self.node1_pos_label = QLabel(dia_hinge_joint)
        self.node1_pos_label.setObjectName(u"node1_pos_label")
        self.node1_pos_label.setGeometry(QRect(70, 50, 171, 31))
        self.node1_pos_label.setFont(font1)
        self.node2_pos_y = QLineEdit(dia_hinge_joint)
        self.node2_pos_y.setObjectName(u"node2_pos_y")
        self.node2_pos_y.setGeometry(QRect(410, 90, 81, 20))
        self.node2_pos_y.setFont(font)
        self.node2_posx_lab = QLabel(dia_hinge_joint)
        self.node2_posx_lab.setObjectName(u"node2_posx_lab")
        self.node2_posx_lab.setGeometry(QRect(320, 70, 81, 21))
        self.node2_posx_lab.setFont(font2)
        self.node2_pos_label = QLabel(dia_hinge_joint)
        self.node2_pos_label.setObjectName(u"node2_pos_label")
        self.node2_pos_label.setGeometry(QRect(380, 50, 171, 31))
        self.node2_pos_label.setFont(font1)
        self.node2_posz_lab = QLabel(dia_hinge_joint)
        self.node2_posz_lab.setObjectName(u"node2_posz_lab")
        self.node2_posz_lab.setGeometry(QRect(500, 70, 81, 21))
        self.node2_posz_lab.setFont(font2)
        self.node2_pos_z = QLineEdit(dia_hinge_joint)
        self.node2_pos_z.setObjectName(u"node2_pos_z")
        self.node2_pos_z.setGeometry(QRect(500, 90, 81, 20))
        self.node2_pos_z.setFont(font)
        self.node2_posy_lab = QLabel(dia_hinge_joint)
        self.node2_posy_lab.setObjectName(u"node2_posy_lab")
        self.node2_posy_lab.setGeometry(QRect(410, 70, 81, 21))
        self.node2_posy_lab.setFont(font2)
        self.node2_pos_x = QLineEdit(dia_hinge_joint)
        self.node2_pos_x.setObjectName(u"node2_pos_x")
        self.node2_pos_x.setGeometry(QRect(320, 90, 81, 20))
        self.node2_pos_x.setFont(font)
        self.node1_OM_type_Box = QComboBox(dia_hinge_joint)
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.setObjectName(u"node1_OM_type_Box")
        self.node1_OM_type_Box.setGeometry(QRect(100, 150, 101, 22))
        self.node1_OM_type_Box.setFont(font)
        self.node1_OM_type_label = QLabel(dia_hinge_joint)
        self.node1_OM_type_label.setObjectName(u"node1_OM_type_label")
        self.node1_OM_type_label.setGeometry(QRect(90, 130, 151, 20))
        self.node1_OM_type_label.setFont(font1)
        self.node1_vect1_x = QLineEdit(dia_hinge_joint)
        self.node1_vect1_x.setObjectName(u"node1_vect1_x")
        self.node1_vect1_x.setGeometry(QRect(20, 200, 81, 20))
        self.node1_vect1_x.setFont(font)
        self.node1_col_x_lab = QLabel(dia_hinge_joint)
        self.node1_col_x_lab.setObjectName(u"node1_col_x_lab")
        self.node1_col_x_lab.setGeometry(QRect(50, 180, 41, 21))
        self.node1_col_x_lab.setFont(font)
        self.node1_col_y_lab = QLabel(dia_hinge_joint)
        self.node1_col_y_lab.setObjectName(u"node1_col_y_lab")
        self.node1_col_y_lab.setGeometry(QRect(140, 180, 41, 21))
        self.node1_col_y_lab.setFont(font)
        self.node1_vect1_y = QLineEdit(dia_hinge_joint)
        self.node1_vect1_y.setObjectName(u"node1_vect1_y")
        self.node1_vect1_y.setGeometry(QRect(110, 200, 81, 20))
        self.node1_vect1_y.setFont(font)
        self.node1_vect1_z = QLineEdit(dia_hinge_joint)
        self.node1_vect1_z.setObjectName(u"node1_vect1_z")
        self.node1_vect1_z.setGeometry(QRect(200, 200, 81, 20))
        self.node1_vect1_z.setFont(font)
        self.node1_col_z_lab = QLabel(dia_hinge_joint)
        self.node1_col_z_lab.setObjectName(u"node1_col_z_lab")
        self.node1_col_z_lab.setGeometry(QRect(230, 180, 41, 21))
        self.node1_col_z_lab.setFont(font)
        self.node1_vect2_z = QLineEdit(dia_hinge_joint)
        self.node1_vect2_z.setObjectName(u"node1_vect2_z")
        self.node1_vect2_z.setGeometry(QRect(200, 230, 81, 20))
        self.node1_vect2_z.setFont(font)
        self.node1_vect2_y = QLineEdit(dia_hinge_joint)
        self.node1_vect2_y.setObjectName(u"node1_vect2_y")
        self.node1_vect2_y.setGeometry(QRect(110, 230, 81, 20))
        self.node1_vect2_y.setFont(font)
        self.node1_vect2_x = QLineEdit(dia_hinge_joint)
        self.node1_vect2_x.setObjectName(u"node1_vect2_x")
        self.node1_vect2_x.setGeometry(QRect(20, 230, 81, 20))
        self.node1_vect2_x.setFont(font)
        self.node1_vect3_z = QLineEdit(dia_hinge_joint)
        self.node1_vect3_z.setObjectName(u"node1_vect3_z")
        self.node1_vect3_z.setGeometry(QRect(200, 260, 81, 20))
        self.node1_vect3_z.setFont(font)
        self.node1_vect3_x = QLineEdit(dia_hinge_joint)
        self.node1_vect3_x.setObjectName(u"node1_vect3_x")
        self.node1_vect3_x.setGeometry(QRect(20, 260, 81, 20))
        self.node1_vect3_x.setFont(font)
        self.node1_vect3_y = QLineEdit(dia_hinge_joint)
        self.node1_vect3_y.setObjectName(u"node1_vect3_y")
        self.node1_vect3_y.setGeometry(QRect(110, 260, 81, 20))
        self.node1_vect3_y.setFont(font)
        self.node1_row_x_lab = QLabel(dia_hinge_joint)
        self.node1_row_x_lab.setObjectName(u"node1_row_x_lab")
        self.node1_row_x_lab.setGeometry(QRect(10, 200, 16, 21))
        self.node1_row_x_lab.setFont(font)
        self.node1_row_2_lab = QLabel(dia_hinge_joint)
        self.node1_row_2_lab.setObjectName(u"node1_row_2_lab")
        self.node1_row_2_lab.setGeometry(QRect(10, 230, 16, 21))
        self.node1_row_2_lab.setFont(font)
        self.node1_row_3_lab = QLabel(dia_hinge_joint)
        self.node1_row_3_lab.setObjectName(u"node1_row_3_lab")
        self.node1_row_3_lab.setGeometry(QRect(10, 260, 16, 21))
        self.node1_row_3_lab.setFont(font)
        self.node2_row_2_lab = QLabel(dia_hinge_joint)
        self.node2_row_2_lab.setObjectName(u"node2_row_2_lab")
        self.node2_row_2_lab.setGeometry(QRect(310, 230, 16, 21))
        self.node2_row_2_lab.setFont(font)
        self.node2_col_x_lab = QLabel(dia_hinge_joint)
        self.node2_col_x_lab.setObjectName(u"node2_col_x_lab")
        self.node2_col_x_lab.setGeometry(QRect(350, 180, 41, 21))
        self.node2_col_x_lab.setFont(font)
        self.node2_vect2_z = QLineEdit(dia_hinge_joint)
        self.node2_vect2_z.setObjectName(u"node2_vect2_z")
        self.node2_vect2_z.setGeometry(QRect(500, 230, 81, 20))
        self.node2_vect2_z.setFont(font)
        self.node2_vect3_z = QLineEdit(dia_hinge_joint)
        self.node2_vect3_z.setObjectName(u"node2_vect3_z")
        self.node2_vect3_z.setGeometry(QRect(500, 260, 81, 20))
        self.node2_vect3_z.setFont(font)
        self.node2_vect3_y = QLineEdit(dia_hinge_joint)
        self.node2_vect3_y.setObjectName(u"node2_vect3_y")
        self.node2_vect3_y.setGeometry(QRect(410, 260, 81, 20))
        self.node2_vect3_y.setFont(font)
        self.node2_row_x_lab = QLabel(dia_hinge_joint)
        self.node2_row_x_lab.setObjectName(u"node2_row_x_lab")
        self.node2_row_x_lab.setGeometry(QRect(310, 200, 16, 21))
        self.node2_row_x_lab.setFont(font)
        self.node2_row_3_lab = QLabel(dia_hinge_joint)
        self.node2_row_3_lab.setObjectName(u"node2_row_3_lab")
        self.node2_row_3_lab.setGeometry(QRect(310, 260, 16, 21))
        self.node2_row_3_lab.setFont(font)
        self.node2_vect2_x = QLineEdit(dia_hinge_joint)
        self.node2_vect2_x.setObjectName(u"node2_vect2_x")
        self.node2_vect2_x.setGeometry(QRect(320, 230, 81, 20))
        self.node2_vect2_x.setFont(font)
        self.node2_vect3_x = QLineEdit(dia_hinge_joint)
        self.node2_vect3_x.setObjectName(u"node2_vect3_x")
        self.node2_vect3_x.setGeometry(QRect(320, 260, 81, 20))
        self.node2_vect3_x.setFont(font)
        self.node2_vect1_z = QLineEdit(dia_hinge_joint)
        self.node2_vect1_z.setObjectName(u"node2_vect1_z")
        self.node2_vect1_z.setGeometry(QRect(500, 200, 81, 20))
        self.node2_vect1_z.setFont(font)
        self.node2_vect1_y = QLineEdit(dia_hinge_joint)
        self.node2_vect1_y.setObjectName(u"node2_vect1_y")
        self.node2_vect1_y.setGeometry(QRect(410, 200, 81, 20))
        self.node2_vect1_y.setFont(font)
        self.node2_col_y_lab = QLabel(dia_hinge_joint)
        self.node2_col_y_lab.setObjectName(u"node2_col_y_lab")
        self.node2_col_y_lab.setGeometry(QRect(440, 180, 41, 21))
        self.node2_col_y_lab.setFont(font)
        self.node2_vect2_y = QLineEdit(dia_hinge_joint)
        self.node2_vect2_y.setObjectName(u"node2_vect2_y")
        self.node2_vect2_y.setGeometry(QRect(410, 230, 81, 20))
        self.node2_vect2_y.setFont(font)
        self.node2_vect1_x = QLineEdit(dia_hinge_joint)
        self.node2_vect1_x.setObjectName(u"node2_vect1_x")
        self.node2_vect1_x.setGeometry(QRect(320, 200, 81, 20))
        self.node2_vect1_x.setFont(font)
        self.node2_col_z_lab = QLabel(dia_hinge_joint)
        self.node2_col_z_lab.setObjectName(u"node2_col_z_lab")
        self.node2_col_z_lab.setGeometry(QRect(530, 180, 41, 21))
        self.node2_col_z_lab.setFont(font)
        self.node2_OM_type_Box = QComboBox(dia_hinge_joint)
        self.node2_OM_type_Box.addItem("")
        self.node2_OM_type_Box.addItem("")
        self.node2_OM_type_Box.addItem("")
        self.node2_OM_type_Box.addItem("")
        self.node2_OM_type_Box.addItem("")
        self.node2_OM_type_Box.addItem("")
        self.node2_OM_type_Box.addItem("")
        self.node2_OM_type_Box.addItem("")
        self.node2_OM_type_Box.setObjectName(u"node2_OM_type_Box")
        self.node2_OM_type_Box.setGeometry(QRect(400, 150, 101, 22))
        self.node2_OM_type_Box.setFont(font)
        self.node2_OM_type_label = QLabel(dia_hinge_joint)
        self.node2_OM_type_label.setObjectName(u"node2_OM_type_label")
        self.node2_OM_type_label.setGeometry(QRect(380, 130, 151, 20))
        self.node2_OM_type_label.setFont(font1)
        self.node1_zaxis_label = QLabel(dia_hinge_joint)
        self.node1_zaxis_label.setObjectName(u"node1_zaxis_label")
        self.node1_zaxis_label.setGeometry(QRect(100, 170, 101, 20))
        font3 = QFont()
        font3.setPointSize(9)
        self.node1_zaxis_label.setFont(font3)
        self.node2_zaxis_label = QLabel(dia_hinge_joint)
        self.node2_zaxis_label.setObjectName(u"node2_zaxis_label")
        self.node2_zaxis_label.setGeometry(QRect(400, 170, 101, 20))
        self.node2_zaxis_label.setFont(font3)

        self.retranslateUi(dia_hinge_joint)
        self.buttonBox.accepted.connect(dia_hinge_joint.accept)
        self.buttonBox.rejected.connect(dia_hinge_joint.reject)

        QMetaObject.connectSlotsByName(dia_hinge_joint)
    # setupUi

    def retranslateUi(self, dia_hinge_joint):
        dia_hinge_joint.setWindowTitle(QCoreApplication.translate("dia_hinge_joint", u"revolute hinge joint", None))
        self.node_1_label.setText(QCoreApplication.translate("dia_hinge_joint", u"node 1", None))
        self.node_2_label.setText(QCoreApplication.translate("dia_hinge_joint", u"node 2", None))
        self.node1_posx_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"node 1 pos. x", None))
        self.node1_posy_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"node 1 pos. y", None))
        self.node1_posz_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"node 1 pos. z", None))
        self.node1_pos_label.setText(QCoreApplication.translate("dia_hinge_joint", u"position relative to node 1", None))
        self.node2_posx_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"node 2 pos. x", None))
        self.node2_pos_label.setText(QCoreApplication.translate("dia_hinge_joint", u"position relative to node 2", None))
        self.node2_posz_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"node 2 pos. z", None))
        self.node2_posy_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"node 2 pos. y", None))
        self.node1_OM_type_Box.setItemText(0, QCoreApplication.translate("dia_hinge_joint", u"xy", None))
        self.node1_OM_type_Box.setItemText(1, QCoreApplication.translate("dia_hinge_joint", u"xz", None))
        self.node1_OM_type_Box.setItemText(2, QCoreApplication.translate("dia_hinge_joint", u"yz", None))
        self.node1_OM_type_Box.setItemText(3, QCoreApplication.translate("dia_hinge_joint", u"matr", None))
        self.node1_OM_type_Box.setItemText(4, QCoreApplication.translate("dia_hinge_joint", u"euler123", None))
        self.node1_OM_type_Box.setItemText(5, QCoreApplication.translate("dia_hinge_joint", u"euler313", None))
        self.node1_OM_type_Box.setItemText(6, QCoreApplication.translate("dia_hinge_joint", u"euler321", None))
        self.node1_OM_type_Box.setItemText(7, QCoreApplication.translate("dia_hinge_joint", u"vector", None))

        self.node1_OM_type_label.setText(QCoreApplication.translate("dia_hinge_joint", u"node 1 orientation matrix", None))
        self.node1_col_x_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"X", None))
        self.node1_col_y_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"Y", None))
        self.node1_col_z_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"Z", None))
        self.node1_row_x_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"1", None))
        self.node1_row_2_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"2", None))
        self.node1_row_3_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"3", None))
        self.node2_row_2_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"2", None))
        self.node2_col_x_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"X", None))
        self.node2_row_x_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"1", None))
        self.node2_row_3_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"3", None))
        self.node2_col_y_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"Y", None))
        self.node2_col_z_lab.setText(QCoreApplication.translate("dia_hinge_joint", u"Z", None))
        self.node2_OM_type_Box.setItemText(0, QCoreApplication.translate("dia_hinge_joint", u"xy", None))
        self.node2_OM_type_Box.setItemText(1, QCoreApplication.translate("dia_hinge_joint", u"xz", None))
        self.node2_OM_type_Box.setItemText(2, QCoreApplication.translate("dia_hinge_joint", u"yz", None))
        self.node2_OM_type_Box.setItemText(3, QCoreApplication.translate("dia_hinge_joint", u"matr", None))
        self.node2_OM_type_Box.setItemText(4, QCoreApplication.translate("dia_hinge_joint", u"euler123", None))
        self.node2_OM_type_Box.setItemText(5, QCoreApplication.translate("dia_hinge_joint", u"euler313", None))
        self.node2_OM_type_Box.setItemText(6, QCoreApplication.translate("dia_hinge_joint", u"euler321", None))
        self.node2_OM_type_Box.setItemText(7, QCoreApplication.translate("dia_hinge_joint", u"vector", None))

        self.node2_OM_type_label.setText(QCoreApplication.translate("dia_hinge_joint", u"node 2 orientation matrix", None))
        self.node1_zaxis_label.setText(QCoreApplication.translate("dia_hinge_joint", u"Z axix is axis of rotation", None))
        self.node2_zaxis_label.setText(QCoreApplication.translate("dia_hinge_joint", u"Z axis is axis of rotation", None))
    # retranslateUi

