# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dia_totalpinjoint.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_dia_Totalpinjoint(object):
    def setupUi(self, dia_Totalpinjoint):
        if dia_Totalpinjoint.objectName():
            dia_Totalpinjoint.setObjectName(u"dia_Totalpinjoint")
        dia_Totalpinjoint.resize(461, 331)
        font = QFont()
        font.setPointSize(10)
        dia_Totalpinjoint.setFont(font)
        self.buttonBox = QDialogButtonBox(dia_Totalpinjoint)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(170, 290, 136, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.node1_box = QComboBox(dia_Totalpinjoint)
        self.node1_box.setObjectName(u"node1_box")
        self.node1_box.setGeometry(QRect(30, 40, 141, 22))
        self.node1_box_lab = QLabel(dia_Totalpinjoint)
        self.node1_box_lab.setObjectName(u"node1_box_lab")
        self.node1_box_lab.setGeometry(QRect(80, 15, 46, 20))
        font1 = QFont()
        font1.setPointSize(12)
        self.node1_box_lab.setFont(font1)
        self.node1_LCS_pos_box = QComboBox(dia_Totalpinjoint)
        self.node1_LCS_pos_box.setObjectName(u"node1_LCS_pos_box")
        self.node1_LCS_pos_box.setGeometry(QRect(30, 80, 141, 22))
        self.fixed_LCS_pos_box = QComboBox(dia_Totalpinjoint)
        self.fixed_LCS_pos_box.setObjectName(u"fixed_LCS_pos_box")
        self.fixed_LCS_pos_box.setGeometry(QRect(290, 80, 141, 22))
        self.node1_LCS_pos_lab = QLabel(dia_Totalpinjoint)
        self.node1_LCS_pos_lab.setObjectName(u"node1_LCS_pos_lab")
        self.node1_LCS_pos_lab.setGeometry(QRect(30, 60, 156, 21))
        self.fixed_LCS_pos_lab = QLabel(dia_Totalpinjoint)
        self.fixed_LCS_pos_lab.setObjectName(u"fixed_LCS_pos_lab")
        self.fixed_LCS_pos_lab.setGeometry(QRect(290, 60, 151, 21))
        self.node1_LCS_rot_box = QComboBox(dia_Totalpinjoint)
        self.node1_LCS_rot_box.setObjectName(u"node1_LCS_rot_box")
        self.node1_LCS_rot_box.setGeometry(QRect(30, 125, 141, 22))
        self.node1_LCS_rot_lab = QLabel(dia_Totalpinjoint)
        self.node1_LCS_rot_lab.setObjectName(u"node1_LCS_rot_lab")
        self.node1_LCS_rot_lab.setGeometry(QRect(30, 105, 156, 21))
        self.fixed_LCS_rot_box = QComboBox(dia_Totalpinjoint)
        self.fixed_LCS_rot_box.setObjectName(u"fixed_LCS_rot_box")
        self.fixed_LCS_rot_box.setGeometry(QRect(290, 125, 141, 22))
        self.fixed_LCS_rot_lab = QLabel(dia_Totalpinjoint)
        self.fixed_LCS_rot_lab.setObjectName(u"fixed_LCS_rot_lab")
        self.fixed_LCS_rot_lab.setGeometry(QRect(290, 105, 156, 21))
        self.constr_lab = QLabel(dia_Totalpinjoint)
        self.constr_lab.setObjectName(u"constr_lab")
        self.constr_lab.setGeometry(QRect(100, 160, 291, 16))
        self.constr_lab.setFont(font)
        self.pos_constr_lab = QLabel(dia_Totalpinjoint)
        self.pos_constr_lab.setObjectName(u"pos_constr_lab")
        self.pos_constr_lab.setGeometry(QRect(20, 185, 86, 16))
        self.pos_constr_lab.setFont(font)
        self.posx_checkBox = QCheckBox(dia_Totalpinjoint)
        self.posx_checkBox.setObjectName(u"posx_checkBox")
        self.posx_checkBox.setGeometry(QRect(130, 185, 53, 14))
        self.posy_checkBox = QCheckBox(dia_Totalpinjoint)
        self.posy_checkBox.setObjectName(u"posy_checkBox")
        self.posy_checkBox.setGeometry(QRect(230, 185, 53, 14))
        self.posz_checkBox = QCheckBox(dia_Totalpinjoint)
        self.posz_checkBox.setObjectName(u"posz_checkBox")
        self.posz_checkBox.setGeometry(QRect(335, 185, 53, 14))
        self.rot_constr_lab = QLabel(dia_Totalpinjoint)
        self.rot_constr_lab.setObjectName(u"rot_constr_lab")
        self.rot_constr_lab.setGeometry(QRect(20, 230, 86, 16))
        self.rot_constr_lab.setFont(font)
        self.roty_checkBox = QCheckBox(dia_Totalpinjoint)
        self.roty_checkBox.setObjectName(u"roty_checkBox")
        self.roty_checkBox.setGeometry(QRect(230, 230, 53, 14))
        self.rotz_checkBox = QCheckBox(dia_Totalpinjoint)
        self.rotz_checkBox.setObjectName(u"rotz_checkBox")
        self.rotz_checkBox.setGeometry(QRect(335, 230, 53, 14))
        self.rotx_checkBox = QCheckBox(dia_Totalpinjoint)
        self.rotx_checkBox.setObjectName(u"rotx_checkBox")
        self.rotx_checkBox.setGeometry(QRect(130, 230, 53, 14))
        self.vel_constr_lab = QLabel(dia_Totalpinjoint)
        self.vel_constr_lab.setObjectName(u"vel_constr_lab")
        self.vel_constr_lab.setGeometry(QRect(20, 200, 86, 16))
        self.vel_constr_lab.setFont(font)
        self.vely_checkBox = QCheckBox(dia_Totalpinjoint)
        self.vely_checkBox.setObjectName(u"vely_checkBox")
        self.vely_checkBox.setGeometry(QRect(230, 200, 53, 14))
        self.velz_checkBox = QCheckBox(dia_Totalpinjoint)
        self.velz_checkBox.setObjectName(u"velz_checkBox")
        self.velz_checkBox.setGeometry(QRect(335, 200, 53, 14))
        self.velx_checkBox = QCheckBox(dia_Totalpinjoint)
        self.velx_checkBox.setObjectName(u"velx_checkBox")
        self.velx_checkBox.setGeometry(QRect(130, 200, 53, 14))
        self.angvelx_checkBox = QCheckBox(dia_Totalpinjoint)
        self.angvelx_checkBox.setObjectName(u"angvelx_checkBox")
        self.angvelx_checkBox.setGeometry(QRect(130, 245, 53, 14))
        self.ang_vel_constr_lab = QLabel(dia_Totalpinjoint)
        self.ang_vel_constr_lab.setObjectName(u"ang_vel_constr_lab")
        self.ang_vel_constr_lab.setGeometry(QRect(20, 245, 86, 16))
        self.ang_vel_constr_lab.setFont(font)
        self.angvelz_checkBox = QCheckBox(dia_Totalpinjoint)
        self.angvelz_checkBox.setObjectName(u"angvelz_checkBox")
        self.angvelz_checkBox.setGeometry(QRect(335, 245, 53, 14))
        self.angvely_checkBox = QCheckBox(dia_Totalpinjoint)
        self.angvely_checkBox.setObjectName(u"angvely_checkBox")
        self.angvely_checkBox.setGeometry(QRect(230, 245, 53, 14))

        self.retranslateUi(dia_Totalpinjoint)
        self.buttonBox.accepted.connect(dia_Totalpinjoint.accept)
        self.buttonBox.rejected.connect(dia_Totalpinjoint.reject)

        QMetaObject.connectSlotsByName(dia_Totalpinjoint)
    # setupUi

    def retranslateUi(self, dia_Totalpinjoint):
        dia_Totalpinjoint.setWindowTitle(QCoreApplication.translate("dia_Totalpinjoint", u"Dialog", None))
        self.node1_box_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"node 1", None))
        self.node1_LCS_pos_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"node 1 LCS pos. offset and orient", None))
        self.fixed_LCS_pos_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"fixed LCS pos. ofset and orient", None))
        self.node1_LCS_rot_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"node 1 LCS rotation orientation", None))
        self.fixed_LCS_rot_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"fixed LCS rotation orientation", None))
        self.constr_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"constraints directions relative to node 1 pos./rot. orientations", None))
        self.pos_constr_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"position constraint", None))
        self.posx_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"pos. x", None))
        self.posy_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"pos. y", None))
        self.posz_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"pos. z", None))
        self.rot_constr_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"position constraint", None))
        self.roty_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"rot. y", None))
        self.rotz_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"rot. z", None))
        self.rotx_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"rot. x", None))
        self.vel_constr_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"velosity constraint", None))
        self.vely_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"vel. y", None))
        self.velz_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"vel. z", None))
        self.velx_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"vel. x", None))
        self.angvelx_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"ang. vel. x", None))
        self.ang_vel_constr_lab.setText(QCoreApplication.translate("dia_Totalpinjoint", u"ang. vel. constraint", None))
        self.angvelz_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"ang. vel. z", None))
        self.angvely_checkBox.setText(QCoreApplication.translate("dia_Totalpinjoint", u"ang. vel. y", None))
    # retranslateUi

