# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dia_sim_config2.ui',
# licensing of 'dia_sim_config2.ui' applies.
#
# Created: Thu Sep 10 23:45:30 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dia_sim_config(object):
    def setupUi(self, dia_sim_config):
        dia_sim_config.setObjectName("dia_sim_config")
        dia_sim_config.resize(368, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dia_sim_config.sizePolicy().hasHeightForWidth())
        dia_sim_config.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(dia_sim_config)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(dia_sim_config)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.bDefault = QtWidgets.QPushButton(self.frame)
        self.bDefault.setObjectName("bDefault")
        self.gridLayout_3.addWidget(self.bDefault, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.ProblemTab = QtWidgets.QWidget()
        self.ProblemTab.setObjectName("ProblemTab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.ProblemTab)
        self.formLayout_2.setObjectName("formLayout_2")
        self.cbInitialTime = QtWidgets.QCheckBox(self.ProblemTab)
        self.cbInitialTime.setChecked(True)
        self.cbInitialTime.setObjectName("cbInitialTime")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cbInitialTime)
        self.leInitialTime = QtWidgets.QLineEdit(self.ProblemTab)
        self.leInitialTime.setObjectName("leInitialTime")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leInitialTime)
        self.cbFinalTime = QtWidgets.QCheckBox(self.ProblemTab)
        self.cbFinalTime.setChecked(True)
        self.cbFinalTime.setObjectName("cbFinalTime")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cbFinalTime)
        self.leFinalTime = QtWidgets.QLineEdit(self.ProblemTab)
        self.leFinalTime.setObjectName("leFinalTime")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leFinalTime)
        self.cbTimeStep = QtWidgets.QCheckBox(self.ProblemTab)
        self.cbTimeStep.setChecked(True)
        self.cbTimeStep.setObjectName("cbTimeStep")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cbTimeStep)
        self.leTimeStep = QtWidgets.QLineEdit(self.ProblemTab)
        self.leTimeStep.setObjectName("leTimeStep")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leTimeStep)
        self.cbMaxIteration = QtWidgets.QCheckBox(self.ProblemTab)
        self.cbMaxIteration.setChecked(True)
        self.cbMaxIteration.setObjectName("cbMaxIteration")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cbMaxIteration)
        self.leMaxIteration = QtWidgets.QLineEdit(self.ProblemTab)
        self.leMaxIteration.setObjectName("leMaxIteration")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.leMaxIteration)
        self.cbOutputFrequency = QtWidgets.QCheckBox(self.ProblemTab)
        self.cbOutputFrequency.setObjectName("cbOutputFrequency")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.cbOutputFrequency)
        self.leOutputFrequency = QtWidgets.QLineEdit(self.ProblemTab)
        self.leOutputFrequency.setEnabled(False)
        self.leOutputFrequency.setObjectName("leOutputFrequency")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.leOutputFrequency)
        self.cbTol = QtWidgets.QCheckBox(self.ProblemTab)
        self.cbTol.setChecked(True)
        self.cbTol.setObjectName("cbTol")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.cbTol)
        self.leTol = QtWidgets.QLineEdit(self.ProblemTab)
        self.leTol.setObjectName("leTol")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.leTol)
        self.cdDerTol = QtWidgets.QCheckBox(self.ProblemTab)
        self.cdDerTol.setObjectName("cdDerTol")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.cdDerTol)
        self.leDerTol = QtWidgets.QLineEdit(self.ProblemTab)
        self.leDerTol.setEnabled(False)
        self.leDerTol.setObjectName("leDerTol")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.leDerTol)
        self.cdOutput = QtWidgets.QCheckBox(self.ProblemTab)
        self.cdOutput.setObjectName("cdOutput")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.cdOutput)
        self.leOutput = QtWidgets.QLineEdit(self.ProblemTab)
        self.leOutput.setEnabled(False)
        self.leOutput.setObjectName("leOutput")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.leOutput)
        self.cdMethod = QtWidgets.QCheckBox(self.ProblemTab)
        self.cdMethod.setObjectName("cdMethod")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.cdMethod)
        self.method = QtWidgets.QComboBox(self.ProblemTab)
        self.method.setEnabled(False)
        self.method.setObjectName("method")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.method)
        self.methods_stack = QtWidgets.QStackedWidget(self.ProblemTab)
        self.methods_stack.setEnabled(True)
        self.methods_stack.setGeometry(QtCore.QRect(235, 330, 212, 90))
        self.methods_stack.setObjectName("methods_stack")
        self.select = QtWidgets.QWidget()
        self.select.setObjectName("select")
        self.methods_stack.addWidget(self.select)
        self.cn = QtWidgets.QWidget()
        self.cn.setObjectName("cn")
        self.methods_stack.addWidget(self.cn)
        self.ms = QtWidgets.QWidget()
        self.ms.setObjectName("ms")
        self.formLayout_3 = QtWidgets.QFormLayout(self.ms)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.ms)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ms_differential_radius = QtWidgets.QLineEdit(self.ms)
        self.ms_differential_radius.setObjectName("ms_differential_radius")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ms_differential_radius)
        self.label_2 = QtWidgets.QLabel(self.ms)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ms_algebraic_radius = QtWidgets.QLineEdit(self.ms)
        self.ms_algebraic_radius.setObjectName("ms_algebraic_radius")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ms_algebraic_radius)
        self.methods_stack.addWidget(self.ms)
        self.hope = QtWidgets.QWidget()
        self.hope.setObjectName("hope")
        self.formLayout_4 = QtWidgets.QFormLayout(self.hope)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.hope)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.hope_differential_radius = QtWidgets.QLineEdit(self.hope)
        self.hope_differential_radius.setObjectName("hope_differential_radius")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hope_differential_radius)
        self.label_4 = QtWidgets.QLabel(self.hope)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hope_algebraic_radius = QtWidgets.QLineEdit(self.hope)
        self.hope_algebraic_radius.setObjectName("hope_algebraic_radius")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hope_algebraic_radius)
        self.methods_stack.addWidget(self.hope)
        self.thirdOrder = QtWidgets.QWidget()
        self.thirdOrder.setObjectName("thirdOrder")
        self.formLayout_5 = QtWidgets.QFormLayout(self.thirdOrder)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_5 = QtWidgets.QLabel(self.thirdOrder)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.thirdOrder_algebraic_radius = QtWidgets.QLineEdit(self.thirdOrder)
        self.thirdOrder_algebraic_radius.setObjectName("thirdOrder_algebraic_radius")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.thirdOrder_algebraic_radius)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(0, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.methods_stack.addWidget(self.thirdOrder)
        self.bdf = QtWidgets.QWidget()
        self.bdf.setObjectName("bdf")
        self.formLayout_6 = QtWidgets.QFormLayout(self.bdf)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtWidgets.QLabel(self.bdf)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.bdf_order = QtWidgets.QLineEdit(self.bdf)
        self.bdf_order.setObjectName("bdf_order")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bdf_order)
        spacerItem2 = QtWidgets.QSpacerItem(191, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_6.setItem(0, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_6.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.methods_stack.addWidget(self.bdf)
        self.ie = QtWidgets.QWidget()
        self.ie.setObjectName("ie")
        self.methods_stack.addWidget(self.ie)
        self.tabWidget.addTab(self.ProblemTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.frame)

        self.retranslateUi(dia_sim_config)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dia_sim_config.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dia_sim_config.reject)
        QtCore.QObject.connect(self.bDefault, QtCore.SIGNAL("clicked()"), dia_sim_config.setDefault)
        QtCore.QMetaObject.connectSlotsByName(dia_sim_config)

    def retranslateUi(self, dia_sim_config):
        dia_sim_config.setWindowTitle(QtWidgets.QApplication.translate("dia_sim_config", "Dialog", None, -1))
        self.bDefault.setText(QtWidgets.QApplication.translate("dia_sim_config", "Default", None, -1))
        self.cbInitialTime.setText(QtWidgets.QApplication.translate("dia_sim_config", "Initial Time", None, -1))
        self.cbFinalTime.setText(QtWidgets.QApplication.translate("dia_sim_config", "Final Time", None, -1))
        self.cbTimeStep.setText(QtWidgets.QApplication.translate("dia_sim_config", "Time Step", None, -1))
        self.cbMaxIteration.setText(QtWidgets.QApplication.translate("dia_sim_config", "Max Iteration", None, -1))
        self.cbOutputFrequency.setText(QtWidgets.QApplication.translate("dia_sim_config", "Output Frequency ( Not Used)", None, -1))
        self.cbTol.setText(QtWidgets.QApplication.translate("dia_sim_config", "Tolerence", None, -1))
        self.cdDerTol.setText(QtWidgets.QApplication.translate("dia_sim_config", "Der. Tolerance", None, -1))
        self.cdOutput.setText(QtWidgets.QApplication.translate("dia_sim_config", "Output(What used For)", None, -1))
        self.leOutput.setText(QtWidgets.QApplication.translate("dia_sim_config", "²", None, -1))
        self.cdMethod.setText(QtWidgets.QApplication.translate("dia_sim_config", "Method", None, -1))
        self.method.setItemText(0, QtWidgets.QApplication.translate("dia_sim_config", "--Select--", None, -1))
        self.method.setItemText(1, QtWidgets.QApplication.translate("dia_sim_config", "Crank Nicolson", None, -1))
        self.method.setItemText(2, QtWidgets.QApplication.translate("dia_sim_config", "ms", None, -1))
        self.method.setItemText(3, QtWidgets.QApplication.translate("dia_sim_config", "Hope", None, -1))
        self.method.setItemText(4, QtWidgets.QApplication.translate("dia_sim_config", "Third Order", None, -1))
        self.method.setItemText(5, QtWidgets.QApplication.translate("dia_sim_config", "bdf", None, -1))
        self.method.setItemText(6, QtWidgets.QApplication.translate("dia_sim_config", "Implicit Euler", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("dia_sim_config", "Dif. radius:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("dia_sim_config", "Alg. radius:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("dia_sim_config", "Dif. radius:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("dia_sim_config", "Alg. radius:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("dia_sim_config", "Alg. radius:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("dia_sim_config", "Order", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ProblemTab), QtWidgets.QApplication.translate("dia_sim_config", "Problem", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("dia_sim_config", "Control Data", None, -1))

