# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_input_file_settings.ui',
# licensing of 'ui_input_file_settings.ui' applies.
#
# Created: Wed Nov 11 14:43:34 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_input_file_settings(object):
    def setupUi(self, input_file_settings):
        input_file_settings.setObjectName("input_file_settings")
        input_file_settings.resize(685, 285)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(input_file_settings.sizePolicy().hasHeightForWidth())
        input_file_settings.setSizePolicy(sizePolicy)
        input_file_settings.setMinimumSize(QtCore.QSize(685, 285))
        input_file_settings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        input_file_settings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(input_file_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(input_file_settings)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_ex_5 = QtWidgets.QLineEdit(self.groupBox)
        self.input_ex_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.input_ex_5.setObjectName("input_ex_5")
        self.gridLayout_2.addWidget(self.input_ex_5, 4, 1, 1, 1)
        self.output_ex_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_ex_5.sizePolicy().hasHeightForWidth())
        self.output_ex_5.setSizePolicy(sizePolicy)
        self.output_ex_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.output_ex_5.setObjectName("output_ex_5")
        self.gridLayout_2.addWidget(self.output_ex_5, 4, 2, 1, 1)
        self.output_ex_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_ex_3.sizePolicy().hasHeightForWidth())
        self.output_ex_3.setSizePolicy(sizePolicy)
        self.output_ex_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.output_ex_3.setObjectName("output_ex_3")
        self.gridLayout_2.addWidget(self.output_ex_3, 2, 2, 1, 1)
        self.output_ex_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_ex_4.sizePolicy().hasHeightForWidth())
        self.output_ex_4.setSizePolicy(sizePolicy)
        self.output_ex_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.output_ex_4.setObjectName("output_ex_4")
        self.gridLayout_2.addWidget(self.output_ex_4, 3, 2, 1, 1)
        self.input_ex_4 = QtWidgets.QLineEdit(self.groupBox)
        self.input_ex_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.input_ex_4.setObjectName("input_ex_4")
        self.gridLayout_2.addWidget(self.input_ex_4, 3, 1, 1, 1)
        self.input_ex_2 = QtWidgets.QLineEdit(self.groupBox)
        self.input_ex_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.input_ex_2.setObjectName("input_ex_2")
        self.gridLayout_2.addWidget(self.input_ex_2, 1, 1, 1, 1)
        self.input_ex_3 = QtWidgets.QLineEdit(self.groupBox)
        self.input_ex_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.input_ex_3.setObjectName("input_ex_3")
        self.gridLayout_2.addWidget(self.input_ex_3, 2, 1, 1, 1)
        self.input_ex_1 = QtWidgets.QLineEdit(self.groupBox)
        self.input_ex_1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.input_ex_1.setObjectName("input_ex_1")
        self.gridLayout_2.addWidget(self.input_ex_1, 0, 1, 1, 1)
        self.format_type = QtWidgets.QComboBox(self.groupBox)
        self.format_type.setObjectName("format_type")
        self.format_type.addItem("")
        self.format_type.addItem("")
        self.gridLayout_2.addWidget(self.format_type, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.total_width = QtWidgets.QSpinBox(self.groupBox)
        self.total_width.setMaximum(30)
        self.total_width.setProperty("value", 1)
        self.total_width.setObjectName("total_width")
        self.horizontalLayout_3.addWidget(self.total_width)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.leading_zeros = QtWidgets.QCheckBox(self.groupBox)
        self.leading_zeros.setEnabled(True)
        self.leading_zeros.setChecked(False)
        self.leading_zeros.setProperty("prefEntry", "KeepResultsOnReRun")
        self.leading_zeros.setProperty("prefPath", "Mod/Mbdyn/General")
        self.leading_zeros.setObjectName("leading_zeros")
        self.horizontalLayout_3.addWidget(self.leading_zeros)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.zero_threshold = QtWidgets.QLineEdit(self.groupBox)
        self.zero_threshold.setObjectName("zero_threshold")
        self.horizontalLayout_6.addWidget(self.zero_threshold)
        self.horizontalLayout_6.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.decimal_number = QtWidgets.QSpinBox(self.groupBox)
        self.decimal_number.setMaximum(30)
        self.decimal_number.setProperty("value", 3)
        self.decimal_number.setObjectName("decimal_number")
        self.horizontalLayout.addWidget(self.decimal_number)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.output_ex_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_ex_2.sizePolicy().hasHeightForWidth())
        self.output_ex_2.setSizePolicy(sizePolicy)
        self.output_ex_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.output_ex_2.setObjectName("output_ex_2")
        self.gridLayout_2.addWidget(self.output_ex_2, 1, 2, 1, 1)
        self.format_spec = QtWidgets.QLabel(self.groupBox)
        self.format_spec.setObjectName("format_spec")
        self.gridLayout_2.addWidget(self.format_spec, 4, 0, 1, 1)
        self.output_ex_1 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_ex_1.sizePolicy().hasHeightForWidth())
        self.output_ex_1.setSizePolicy(sizePolicy)
        self.output_ex_1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.output_ex_1.setObjectName("output_ex_1")
        self.gridLayout_2.addWidget(self.output_ex_1, 0, 2, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 1)
        self.gridLayout_2.setColumnMinimumWidth(1, 10)
        self.gridLayout_2.setColumnMinimumWidth(2, 10)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(input_file_settings)
        QtCore.QMetaObject.connectSlotsByName(input_file_settings)

    def retranslateUi(self, input_file_settings):
        input_file_settings.setWindowTitle(QtWidgets.QApplication.translate("input_file_settings", "Input File", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("input_file_settings", "Float format", None, -1))
        self.output_ex_5.setText(QtWidgets.QApplication.translate("input_file_settings", "input_5", None, -1))
        self.output_ex_3.setText(QtWidgets.QApplication.translate("input_file_settings", "input_3", None, -1))
        self.output_ex_4.setText(QtWidgets.QApplication.translate("input_file_settings", "input_4", None, -1))
        self.format_type.setItemText(0, QtWidgets.QApplication.translate("input_file_settings", "Scientific", None, -1))
        self.format_type.setItemText(1, QtWidgets.QApplication.translate("input_file_settings", "Floating", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("input_file_settings", "total width", None, -1))
        self.leading_zeros.setText(QtWidgets.QApplication.translate("input_file_settings", "Leading zero(s)", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("input_file_settings", "Zero threshold:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("input_file_settings", "number of decimals", None, -1))
        self.output_ex_2.setText(QtWidgets.QApplication.translate("input_file_settings", "input_2", None, -1))
        self.format_spec.setText(QtWidgets.QApplication.translate("input_file_settings", "none", None, -1))
        self.output_ex_1.setText(QtWidgets.QApplication.translate("input_file_settings", "input_1", None, -1))

