# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_solver_settings.ui',
# licensing of 'ui_solver_settings.ui' applies.
#
# Created: Wed Jul 15 23:20:36 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_solver_settings(object):
    def setupUi(self, solver_settings):
        solver_settings.setObjectName("solver_settings")
        solver_settings.resize(702, 306)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(solver_settings.sizePolicy().hasHeightForWidth())
        solver_settings.setSizePolicy(sizePolicy)
        solver_settings.setMinimumSize(QtCore.QSize(685, 285))
        solver_settings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        solver_settings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(solver_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.defaultSolverComboBox = QtWidgets.QComboBox(solver_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultSolverComboBox.sizePolicy().hasHeightForWidth())
        self.defaultSolverComboBox.setSizePolicy(sizePolicy)
        self.defaultSolverComboBox.setMinimumSize(QtCore.QSize(150, 24))
        self.defaultSolverComboBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.defaultSolverComboBox.setObjectName("defaultSolverComboBox")
        self.gridLayout_2.addWidget(self.defaultSolverComboBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(solver_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 24))
        self.label.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.useWSL = QtWidgets.QCheckBox(solver_settings)
        self.useWSL.setMinimumSize(QtCore.QSize(0, 24))
        self.useWSL.setMaximumSize(QtCore.QSize(16777215, 24))
        self.useWSL.setObjectName("useWSL")
        self.gridLayout_2.addWidget(self.useWSL, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.mbdynBinariesPath = QtWidgets.QTableWidget(solver_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mbdynBinariesPath.sizePolicy().hasHeightForWidth())
        self.mbdynBinariesPath.setSizePolicy(sizePolicy)
        self.mbdynBinariesPath.setMinimumSize(QtCore.QSize(100, 300))
        self.mbdynBinariesPath.setMaximumSize(QtCore.QSize(16777215, 600))
        self.mbdynBinariesPath.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mbdynBinariesPath.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.mbdynBinariesPath.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mbdynBinariesPath.setShowGrid(True)
        self.mbdynBinariesPath.setObjectName("mbdynBinariesPath")
        self.mbdynBinariesPath.setColumnCount(2)
        self.mbdynBinariesPath.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mbdynBinariesPath.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mbdynBinariesPath.setHorizontalHeaderItem(1, item)
        self.mbdynBinariesPath.horizontalHeader().setCascadingSectionResizes(False)
        self.mbdynBinariesPath.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.mbdynBinariesPath)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(solver_settings)
        self.label_2.setMinimumSize(QtCore.QSize(0, 24))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.addBinaryPathButton = QtWidgets.QPushButton(solver_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addBinaryPathButton.sizePolicy().hasHeightForWidth())
        self.addBinaryPathButton.setSizePolicy(sizePolicy)
        self.addBinaryPathButton.setMinimumSize(QtCore.QSize(24, 24))
        self.addBinaryPathButton.setMaximumSize(QtCore.QSize(24, 24))
        self.addBinaryPathButton.setText("")
        self.addBinaryPathButton.setObjectName("addBinaryPathButton")
        self.gridLayout.addWidget(self.addBinaryPathButton, 1, 3, 1, 1)
        self.activeBinaryName = QtWidgets.QLineEdit(solver_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeBinaryName.sizePolicy().hasHeightForWidth())
        self.activeBinaryName.setSizePolicy(sizePolicy)
        self.activeBinaryName.setMinimumSize(QtCore.QSize(0, 24))
        self.activeBinaryName.setMaximumSize(QtCore.QSize(16777215, 24))
        self.activeBinaryName.setPlaceholderText("")
        self.activeBinaryName.setObjectName("activeBinaryName")
        self.gridLayout.addWidget(self.activeBinaryName, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(solver_settings)
        self.label_3.setMinimumSize(QtCore.QSize(0, 24))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.rmvBinaryPathButton = QtWidgets.QPushButton(solver_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rmvBinaryPathButton.sizePolicy().hasHeightForWidth())
        self.rmvBinaryPathButton.setSizePolicy(sizePolicy)
        self.rmvBinaryPathButton.setMinimumSize(QtCore.QSize(24, 24))
        self.rmvBinaryPathButton.setMaximumSize(QtCore.QSize(24, 24))
        self.rmvBinaryPathButton.setText("")
        self.rmvBinaryPathButton.setObjectName("rmvBinaryPathButton")
        self.gridLayout.addWidget(self.rmvBinaryPathButton, 1, 4, 1, 1)
        self.selectBinaryPathButton = QtWidgets.QPushButton(solver_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBinaryPathButton.sizePolicy().hasHeightForWidth())
        self.selectBinaryPathButton.setSizePolicy(sizePolicy)
        self.selectBinaryPathButton.setMinimumSize(QtCore.QSize(0, 24))
        self.selectBinaryPathButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.selectBinaryPathButton.setObjectName("selectBinaryPathButton")
        self.gridLayout.addWidget(self.selectBinaryPathButton, 1, 2, 1, 1)
        self.activeBinaryPath = QtWidgets.QLineEdit(solver_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeBinaryPath.sizePolicy().hasHeightForWidth())
        self.activeBinaryPath.setSizePolicy(sizePolicy)
        self.activeBinaryPath.setMinimumSize(QtCore.QSize(0, 24))
        self.activeBinaryPath.setMaximumSize(QtCore.QSize(16777215, 24))
        self.activeBinaryPath.setPlaceholderText("")
        self.activeBinaryPath.setObjectName("activeBinaryPath")
        self.gridLayout.addWidget(self.activeBinaryPath, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 2000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(solver_settings)
        QtCore.QMetaObject.connectSlotsByName(solver_settings)

    def retranslateUi(self, solver_settings):
        solver_settings.setWindowTitle(QtWidgets.QApplication.translate("solver_settings", "Solver", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("solver_settings", "Default Solver", None, -1))
        self.useWSL.setToolTip(QtWidgets.QApplication.translate("solver_settings", "<html><head/><body><p>WSL: Windows Subsystem for Linux</p></body></html>", None, -1))
        self.useWSL.setText(QtWidgets.QApplication.translate("solver_settings", "Use WSL (Windows Only)", None, -1))
        self.mbdynBinariesPath.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("solver_settings", "Name", None, -1))
        self.mbdynBinariesPath.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("solver_settings", "Path", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("solver_settings", "Name", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("solver_settings", "Path (including executable)", None, -1))
        self.selectBinaryPathButton.setText(QtWidgets.QApplication.translate("solver_settings", "Browse...", None, -1))

