# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dia_gravity_field.ui',
# licensing of 'dia_gravity_field.ui' applies.
#
# Created: Sat Sep 19 10:57:29 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dia_gravity_field(object):
    def setupUi(self, dia_gravity_field):
        dia_gravity_field.setObjectName("dia_gravity_field")
        dia_gravity_field.resize(302, 248)
        self.formLayout_2 = QtWidgets.QFormLayout(dia_gravity_field)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(dia_gravity_field)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cbGravityType = QtWidgets.QComboBox(dia_gravity_field)
        self.cbGravityType.setModelColumn(0)
        self.cbGravityType.setObjectName("cbGravityType")
        self.cbGravityType.addItem("")
        self.cbGravityType.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbGravityType)
        self.swGravityParam = QtWidgets.QStackedWidget(dia_gravity_field)
        self.swGravityParam.setObjectName("swGravityParam")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayout = QtWidgets.QFormLayout(self.page)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.leGravAcceleration = QtWidgets.QLineEdit(self.page)
        self.leGravAcceleration.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.leGravAcceleration.setText("")
        self.leGravAcceleration.setObjectName("leGravAcceleration")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leGravAcceleration)
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.leUniformVx = QtWidgets.QLineEdit(self.groupBox)
        self.leUniformVx.setObjectName("leUniformVx")
        self.gridLayout_4.addWidget(self.leUniformVx, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.leUniformVy = QtWidgets.QLineEdit(self.groupBox)
        self.leUniformVy.setObjectName("leUniformVy")
        self.gridLayout_4.addWidget(self.leUniformVy, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.leUniformVz = QtWidgets.QLineEdit(self.groupBox)
        self.leUniformVz.setObjectName("leUniformVz")
        self.gridLayout_4.addWidget(self.leUniformVz, 2, 1, 1, 1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.swGravityParam.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.page_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.leCgFieldMass = QtWidgets.QLineEdit(self.page_2)
        self.leCgFieldMass.setObjectName("leCgFieldMass")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leCgFieldMass)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.leGravConstant = QtWidgets.QLineEdit(self.page_2)
        self.leGravConstant.setObjectName("leGravConstant")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leGravConstant)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.leCentralOx = QtWidgets.QLineEdit(self.groupBox_2)
        self.leCentralOx.setObjectName("leCentralOx")
        self.gridLayout.addWidget(self.leCentralOx, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.leCentralOy = QtWidgets.QLineEdit(self.groupBox_2)
        self.leCentralOy.setObjectName("leCentralOy")
        self.gridLayout.addWidget(self.leCentralOy, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.leCentralOz = QtWidgets.QLineEdit(self.groupBox_2)
        self.leCentralOz.setObjectName("leCentralOz")
        self.gridLayout.addWidget(self.leCentralOz, 2, 1, 1, 1)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        self.swGravityParam.addWidget(self.page_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.swGravityParam)
        self.buttonBox = QtWidgets.QDialogButtonBox(dia_gravity_field)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(dia_gravity_field)
        self.cbGravityType.setCurrentIndex(0)
        self.swGravityParam.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dia_gravity_field.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dia_gravity_field.reject)
        QtCore.QObject.connect(self.cbGravityType, QtCore.SIGNAL("currentIndexChanged(int)"), self.swGravityParam.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(dia_gravity_field)

    def retranslateUi(self, dia_gravity_field):
        dia_gravity_field.setWindowTitle(QtWidgets.QApplication.translate("dia_gravity_field", "Gravity Field", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("dia_gravity_field", "Type", None, -1))
        self.cbGravityType.setItemText(0, QtWidgets.QApplication.translate("dia_gravity_field", "Uniform", None, -1))
        self.cbGravityType.setItemText(1, QtWidgets.QApplication.translate("dia_gravity_field", "Central", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("dia_gravity_field", "Gravity Acceleration", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("dia_gravity_field", "Direction", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("dia_gravity_field", "X:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("dia_gravity_field", "Y:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("dia_gravity_field", "Z:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("dia_gravity_field", "CG Field Mass", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("dia_gravity_field", "Gravity Constant", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("dia_gravity_field", "Absolute Origin:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("dia_gravity_field", "X:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("dia_gravity_field", "Y:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("dia_gravity_field", "Z:", None, -1))

