# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dia_totaljoint.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_dia_Totaljoint(object):
    def setupUi(self, dia_Totaljoint):
        if dia_Totaljoint.objectName():
            dia_Totaljoint.setObjectName(u"dia_Totaljoint")
        dia_Totaljoint.resize(461, 349)
        font = QFont()
        font.setPointSize(10)
        dia_Totaljoint.setFont(font)
        self.buttonBox = QDialogButtonBox(dia_Totaljoint)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(170, 315, 136, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.node1_box = QComboBox(dia_Totaljoint)
        self.node1_box.setObjectName(u"node1_box")
        self.node1_box.setGeometry(QRect(30, 30, 141, 22))
        self.node2_box = QComboBox(dia_Totaljoint)
        self.node2_box.setObjectName(u"node2_box")
        self.node2_box.setGeometry(QRect(290, 30, 141, 22))
        self.node1_box_lab = QLabel(dia_Totaljoint)
        self.node1_box_lab.setObjectName(u"node1_box_lab")
        self.node1_box_lab.setGeometry(QRect(80, 10, 46, 20))
        font1 = QFont()
        font1.setPointSize(12)
        self.node1_box_lab.setFont(font1)
        self.node2_box_lab = QLabel(dia_Totaljoint)
        self.node2_box_lab.setObjectName(u"node2_box_lab")
        self.node2_box_lab.setGeometry(QRect(340, 9, 35, 21))
        self.node2_box_lab.setFont(font1)
        self.node1_LCS_pos_box = QComboBox(dia_Totaljoint)
        self.node1_LCS_pos_box.setObjectName(u"node1_LCS_pos_box")
        self.node1_LCS_pos_box.setGeometry(QRect(30, 80, 141, 22))
        self.node2_LCS_pos_box = QComboBox(dia_Totaljoint)
        self.node2_LCS_pos_box.setObjectName(u"node2_LCS_pos_box")
        self.node2_LCS_pos_box.setGeometry(QRect(290, 80, 141, 22))
        self.node1_LCS_pos_lab = QLabel(dia_Totaljoint)
        self.node1_LCS_pos_lab.setObjectName(u"node1_LCS_pos_lab")
        self.node1_LCS_pos_lab.setGeometry(QRect(30, 60, 156, 21))
        self.node2_LCS_pos_lab = QLabel(dia_Totaljoint)
        self.node2_LCS_pos_lab.setObjectName(u"node2_LCS_pos_lab")
        self.node2_LCS_pos_lab.setGeometry(QRect(290, 60, 151, 21))
        self.node1_LCS_rot_box = QComboBox(dia_Totaljoint)
        self.node1_LCS_rot_box.setObjectName(u"node1_LCS_rot_box")
        self.node1_LCS_rot_box.setGeometry(QRect(30, 125, 141, 22))
        self.node1_LCS_rot_lab = QLabel(dia_Totaljoint)
        self.node1_LCS_rot_lab.setObjectName(u"node1_LCS_rot_lab")
        self.node1_LCS_rot_lab.setGeometry(QRect(30, 105, 156, 21))
        self.node2_LCS_rot_box = QComboBox(dia_Totaljoint)
        self.node2_LCS_rot_box.setObjectName(u"node2_LCS_rot_box")
        self.node2_LCS_rot_box.setGeometry(QRect(290, 125, 141, 22))
        self.node2_LCS_rot_lab = QLabel(dia_Totaljoint)
        self.node2_LCS_rot_lab.setObjectName(u"node2_LCS_rot_lab")
        self.node2_LCS_rot_lab.setGeometry(QRect(290, 105, 156, 21))
        self.constr_lab = QLabel(dia_Totaljoint)
        self.constr_lab.setObjectName(u"constr_lab")
        self.constr_lab.setGeometry(QRect(100, 160, 291, 16))
        self.constr_lab.setFont(font)
        self.pos_constr_lab = QLabel(dia_Totaljoint)
        self.pos_constr_lab.setObjectName(u"pos_constr_lab")
        self.pos_constr_lab.setGeometry(QRect(20, 185, 86, 16))
        self.pos_constr_lab.setFont(font)
        self.posx_checkBox = QCheckBox(dia_Totaljoint)
        self.posx_checkBox.setObjectName(u"posx_checkBox")
        self.posx_checkBox.setGeometry(QRect(130, 185, 53, 14))
        self.posy_checkBox = QCheckBox(dia_Totaljoint)
        self.posy_checkBox.setObjectName(u"posy_checkBox")
        self.posy_checkBox.setGeometry(QRect(230, 185, 53, 14))
        self.posz_checkBox = QCheckBox(dia_Totaljoint)
        self.posz_checkBox.setObjectName(u"posz_checkBox")
        self.posz_checkBox.setGeometry(QRect(335, 185, 53, 14))
        self.rot_constr_lab = QLabel(dia_Totaljoint)
        self.rot_constr_lab.setObjectName(u"rot_constr_lab")
        self.rot_constr_lab.setGeometry(QRect(20, 230, 86, 16))
        self.rot_constr_lab.setFont(font)
        self.roty_checkBox = QCheckBox(dia_Totaljoint)
        self.roty_checkBox.setObjectName(u"roty_checkBox")
        self.roty_checkBox.setGeometry(QRect(230, 230, 53, 14))
        self.rotz_checkBox = QCheckBox(dia_Totaljoint)
        self.rotz_checkBox.setObjectName(u"rotz_checkBox")
        self.rotz_checkBox.setGeometry(QRect(335, 230, 53, 14))
        self.rotx_checkBox = QCheckBox(dia_Totaljoint)
        self.rotx_checkBox.setObjectName(u"rotx_checkBox")
        self.rotx_checkBox.setGeometry(QRect(130, 230, 53, 14))
        self.vel_constr_lab = QLabel(dia_Totaljoint)
        self.vel_constr_lab.setObjectName(u"vel_constr_lab")
        self.vel_constr_lab.setGeometry(QRect(20, 200, 86, 16))
        self.vel_constr_lab.setFont(font)
        self.vely_checkBox = QCheckBox(dia_Totaljoint)
        self.vely_checkBox.setObjectName(u"vely_checkBox")
        self.vely_checkBox.setGeometry(QRect(230, 200, 53, 14))
        self.velz_checkBox = QCheckBox(dia_Totaljoint)
        self.velz_checkBox.setObjectName(u"velz_checkBox")
        self.velz_checkBox.setGeometry(QRect(335, 200, 53, 14))
        self.velx_checkBox = QCheckBox(dia_Totaljoint)
        self.velx_checkBox.setObjectName(u"velx_checkBox")
        self.velx_checkBox.setGeometry(QRect(130, 200, 53, 14))
        self.angvelx_checkBox = QCheckBox(dia_Totaljoint)
        self.angvelx_checkBox.setObjectName(u"angvelx_checkBox")
        self.angvelx_checkBox.setGeometry(QRect(130, 245, 53, 14))
        self.ang_vel_constr_lab = QLabel(dia_Totaljoint)
        self.ang_vel_constr_lab.setObjectName(u"ang_vel_constr_lab")
        self.ang_vel_constr_lab.setGeometry(QRect(20, 245, 86, 16))
        self.ang_vel_constr_lab.setFont(font)
        self.angvelz_checkBox = QCheckBox(dia_Totaljoint)
        self.angvelz_checkBox.setObjectName(u"angvelz_checkBox")
        self.angvelz_checkBox.setGeometry(QRect(335, 245, 53, 14))
        self.angvely_checkBox = QCheckBox(dia_Totaljoint)
        self.angvely_checkBox.setObjectName(u"angvely_checkBox")
        self.angvely_checkBox.setGeometry(QRect(230, 245, 53, 14))
        self.drivecall_lab = QLabel(dia_Totaljoint)
        self.drivecall_lab.setObjectName(u"drivecall_lab")
        self.drivecall_lab.setGeometry(QRect(179, 270, 116, 16))
        self.drivecall_Box = QComboBox(dia_Totaljoint)
        self.drivecall_Box.setObjectName(u"drivecall_Box")
        self.drivecall_Box.setGeometry(QRect(175, 290, 126, 22))
        self.create_drive_Button = QPushButton(dia_Totaljoint)
        self.create_drive_Button.setObjectName(u"create_drive_Button")
        self.create_drive_Button.setGeometry(QRect(44, 290, 101, 21))

        self.retranslateUi(dia_Totaljoint)
        self.buttonBox.accepted.connect(dia_Totaljoint.accept)
        self.buttonBox.rejected.connect(dia_Totaljoint.reject)

        QMetaObject.connectSlotsByName(dia_Totaljoint)
    # setupUi

    def retranslateUi(self, dia_Totaljoint):
        dia_Totaljoint.setWindowTitle(QCoreApplication.translate("dia_Totaljoint", u"Dialog total joint", None))
        self.node1_box_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"node 1", None))
        self.node2_box_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"node 2", None))
        self.node1_LCS_pos_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"node 1 LCS pos. offset and orient", None))
        self.node2_LCS_pos_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"node 2 LCS pos. ofset and orient", None))
        self.node1_LCS_rot_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"node 1 LCS rotation orientation", None))
        self.node2_LCS_rot_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"node 2 LCS rotation orientation", None))
        self.constr_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"constraints directions relative to node 1 pos./rot. orientations", None))
        self.pos_constr_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"position constraint", None))
        self.posx_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"pos. x", None))
        self.posy_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"pos. y", None))
        self.posz_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"pos. z", None))
        self.rot_constr_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"rotation constraint", None))
        self.roty_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"rot. y", None))
        self.rotz_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"rot. z", None))
        self.rotx_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"rot. x", None))
        self.vel_constr_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"velosity constraint", None))
        self.vely_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"vel. y", None))
        self.velz_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"vel. z", None))
        self.velx_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"vel. x", None))
        self.angvelx_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"ang. vel. x", None))
        self.ang_vel_constr_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"ang. vel. constraint", None))
        self.angvelz_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"ang. vel. z", None))
        self.angvely_checkBox.setText(QCoreApplication.translate("dia_Totaljoint", u"ang. vel. y", None))
        self.drivecall_lab.setText(QCoreApplication.translate("dia_Totaljoint", u"drive_caller", None))
        self.create_drive_Button.setText(QCoreApplication.translate("dia_Totaljoint", u"create template drive", None))
    # retranslateUi

