# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dia_revpin_joint.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_dia_revpin_joint(object):
    def setupUi(self, dia_revpin_joint):
        if dia_revpin_joint.objectName():
            dia_revpin_joint.setObjectName(u"dia_revpin_joint")
        dia_revpin_joint.resize(600, 400)
        self.buttonBox = QDialogButtonBox(dia_revpin_joint)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(40, 370, 341, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.node_1_Box = QComboBox(dia_revpin_joint)
        self.node_1_Box.setObjectName(u"node_1_Box")
        self.node_1_Box.setGeometry(QRect(240, 20, 101, 22))
        font = QFont()
        font.setPointSize(10)
        self.node_1_Box.setFont(font)
        self.node_1_label = QLabel(dia_revpin_joint)
        self.node_1_label.setObjectName(u"node_1_label")
        self.node_1_label.setGeometry(QRect(240, 0, 91, 21))
        font1 = QFont()
        font1.setPointSize(12)
        self.node_1_label.setFont(font1)
        self.node1_pos_x = QLineEdit(dia_revpin_joint)
        self.node1_pos_x.setObjectName(u"node1_pos_x")
        self.node1_pos_x.setGeometry(QRect(20, 90, 81, 20))
        self.node1_pos_x.setFont(font)
        self.node1_posx_lab = QLabel(dia_revpin_joint)
        self.node1_posx_lab.setObjectName(u"node1_posx_lab")
        self.node1_posx_lab.setGeometry(QRect(20, 70, 81, 21))
        font2 = QFont()
        font2.setPointSize(11)
        self.node1_posx_lab.setFont(font2)
        self.node1_pos_y = QLineEdit(dia_revpin_joint)
        self.node1_pos_y.setObjectName(u"node1_pos_y")
        self.node1_pos_y.setGeometry(QRect(110, 90, 81, 20))
        self.node1_pos_y.setFont(font)
        self.node1_posy_lab = QLabel(dia_revpin_joint)
        self.node1_posy_lab.setObjectName(u"node1_posy_lab")
        self.node1_posy_lab.setGeometry(QRect(110, 70, 81, 21))
        self.node1_posy_lab.setFont(font2)
        self.node1_pos_z = QLineEdit(dia_revpin_joint)
        self.node1_pos_z.setObjectName(u"node1_pos_z")
        self.node1_pos_z.setGeometry(QRect(200, 90, 81, 20))
        self.node1_pos_z.setFont(font)
        self.node1_posz_lab = QLabel(dia_revpin_joint)
        self.node1_posz_lab.setObjectName(u"node1_posz_lab")
        self.node1_posz_lab.setGeometry(QRect(200, 70, 81, 21))
        self.node1_posz_lab.setFont(font2)
        self.node1_pos_label = QLabel(dia_revpin_joint)
        self.node1_pos_label.setObjectName(u"node1_pos_label")
        self.node1_pos_label.setGeometry(QRect(70, 50, 171, 31))
        self.node1_pos_label.setFont(font1)
        self.fixed_pos_y = QLineEdit(dia_revpin_joint)
        self.fixed_pos_y.setObjectName(u"fixed_pos_y")
        self.fixed_pos_y.setGeometry(QRect(410, 90, 81, 20))
        self.fixed_pos_y.setFont(font)
        self.fixed_posx_lab = QLabel(dia_revpin_joint)
        self.fixed_posx_lab.setObjectName(u"fixed_posx_lab")
        self.fixed_posx_lab.setGeometry(QRect(320, 70, 81, 21))
        self.fixed_posx_lab.setFont(font2)
        self.fixed_pos_label = QLabel(dia_revpin_joint)
        self.fixed_pos_label.setObjectName(u"fixed_pos_label")
        self.fixed_pos_label.setGeometry(QRect(380, 50, 171, 31))
        self.fixed_pos_label.setFont(font1)
        self.fixed_posz_lab = QLabel(dia_revpin_joint)
        self.fixed_posz_lab.setObjectName(u"fixed_posz_lab")
        self.fixed_posz_lab.setGeometry(QRect(500, 70, 81, 21))
        self.fixed_posz_lab.setFont(font2)
        self.fixed_pos_z = QLineEdit(dia_revpin_joint)
        self.fixed_pos_z.setObjectName(u"fixed_pos_z")
        self.fixed_pos_z.setGeometry(QRect(500, 90, 81, 20))
        self.fixed_pos_z.setFont(font)
        self.fixed_posy_lab = QLabel(dia_revpin_joint)
        self.fixed_posy_lab.setObjectName(u"fixed_posy_lab")
        self.fixed_posy_lab.setGeometry(QRect(410, 70, 81, 21))
        self.fixed_posy_lab.setFont(font2)
        self.fixed_pos_x = QLineEdit(dia_revpin_joint)
        self.fixed_pos_x.setObjectName(u"fixed_pos_x")
        self.fixed_pos_x.setGeometry(QRect(320, 90, 81, 20))
        self.fixed_pos_x.setFont(font)
        self.node1_OM_type_Box = QComboBox(dia_revpin_joint)
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.addItem("")
        self.node1_OM_type_Box.setObjectName(u"node1_OM_type_Box")
        self.node1_OM_type_Box.setGeometry(QRect(100, 200, 101, 22))
        self.node1_OM_type_Box.setFont(font)
        self.node1_vect1_x = QLineEdit(dia_revpin_joint)
        self.node1_vect1_x.setObjectName(u"node1_vect1_x")
        self.node1_vect1_x.setGeometry(QRect(20, 280, 81, 20))
        self.node1_vect1_x.setFont(font)
        self.node1_col_x_lab = QLabel(dia_revpin_joint)
        self.node1_col_x_lab.setObjectName(u"node1_col_x_lab")
        self.node1_col_x_lab.setGeometry(QRect(50, 260, 41, 21))
        self.node1_col_x_lab.setFont(font)
        self.node1_col_y_lab = QLabel(dia_revpin_joint)
        self.node1_col_y_lab.setObjectName(u"node1_col_y_lab")
        self.node1_col_y_lab.setGeometry(QRect(140, 260, 41, 21))
        self.node1_col_y_lab.setFont(font)
        self.node1_vect1_y = QLineEdit(dia_revpin_joint)
        self.node1_vect1_y.setObjectName(u"node1_vect1_y")
        self.node1_vect1_y.setGeometry(QRect(110, 280, 81, 20))
        self.node1_vect1_y.setFont(font)
        self.node1_vect1_z = QLineEdit(dia_revpin_joint)
        self.node1_vect1_z.setObjectName(u"node1_vect1_z")
        self.node1_vect1_z.setGeometry(QRect(200, 280, 81, 20))
        self.node1_vect1_z.setFont(font)
        self.node1_col_z_lab = QLabel(dia_revpin_joint)
        self.node1_col_z_lab.setObjectName(u"node1_col_z_lab")
        self.node1_col_z_lab.setGeometry(QRect(230, 260, 41, 21))
        self.node1_col_z_lab.setFont(font)
        self.node1_vect2_z = QLineEdit(dia_revpin_joint)
        self.node1_vect2_z.setObjectName(u"node1_vect2_z")
        self.node1_vect2_z.setGeometry(QRect(200, 310, 81, 20))
        self.node1_vect2_z.setFont(font)
        self.node1_vect2_y = QLineEdit(dia_revpin_joint)
        self.node1_vect2_y.setObjectName(u"node1_vect2_y")
        self.node1_vect2_y.setGeometry(QRect(110, 310, 81, 20))
        self.node1_vect2_y.setFont(font)
        self.node1_vect2_x = QLineEdit(dia_revpin_joint)
        self.node1_vect2_x.setObjectName(u"node1_vect2_x")
        self.node1_vect2_x.setGeometry(QRect(20, 310, 81, 20))
        self.node1_vect2_x.setFont(font)
        self.node1_vect3_z = QLineEdit(dia_revpin_joint)
        self.node1_vect3_z.setObjectName(u"node1_vect3_z")
        self.node1_vect3_z.setGeometry(QRect(200, 340, 81, 20))
        self.node1_vect3_z.setFont(font)
        self.node1_vect3_x = QLineEdit(dia_revpin_joint)
        self.node1_vect3_x.setObjectName(u"node1_vect3_x")
        self.node1_vect3_x.setGeometry(QRect(20, 340, 81, 20))
        self.node1_vect3_x.setFont(font)
        self.node1_vect3_y = QLineEdit(dia_revpin_joint)
        self.node1_vect3_y.setObjectName(u"node1_vect3_y")
        self.node1_vect3_y.setGeometry(QRect(110, 340, 81, 20))
        self.node1_vect3_y.setFont(font)
        self.node1_row_x_lab = QLabel(dia_revpin_joint)
        self.node1_row_x_lab.setObjectName(u"node1_row_x_lab")
        self.node1_row_x_lab.setGeometry(QRect(10, 280, 16, 21))
        self.node1_row_x_lab.setFont(font)
        self.node1_row_2_lab = QLabel(dia_revpin_joint)
        self.node1_row_2_lab.setObjectName(u"node1_row_2_lab")
        self.node1_row_2_lab.setGeometry(QRect(10, 310, 16, 21))
        self.node1_row_2_lab.setFont(font)
        self.node1_row_3_lab = QLabel(dia_revpin_joint)
        self.node1_row_3_lab.setObjectName(u"node1_row_3_lab")
        self.node1_row_3_lab.setGeometry(QRect(10, 340, 16, 21))
        self.node1_row_3_lab.setFont(font)
        self.fixed_row_2_lab = QLabel(dia_revpin_joint)
        self.fixed_row_2_lab.setObjectName(u"fixed_row_2_lab")
        self.fixed_row_2_lab.setGeometry(QRect(310, 310, 16, 21))
        self.fixed_row_2_lab.setFont(font)
        self.fixed_col_x_lab = QLabel(dia_revpin_joint)
        self.fixed_col_x_lab.setObjectName(u"fixed_col_x_lab")
        self.fixed_col_x_lab.setGeometry(QRect(350, 260, 41, 21))
        self.fixed_col_x_lab.setFont(font)
        self.fixed_vect2_z = QLineEdit(dia_revpin_joint)
        self.fixed_vect2_z.setObjectName(u"fixed_vect2_z")
        self.fixed_vect2_z.setGeometry(QRect(500, 310, 81, 20))
        self.fixed_vect2_z.setFont(font)
        self.fixed_vect3_z = QLineEdit(dia_revpin_joint)
        self.fixed_vect3_z.setObjectName(u"fixed_vect3_z")
        self.fixed_vect3_z.setGeometry(QRect(500, 340, 81, 20))
        self.fixed_vect3_z.setFont(font)
        self.fixed_vect3_y = QLineEdit(dia_revpin_joint)
        self.fixed_vect3_y.setObjectName(u"fixed_vect3_y")
        self.fixed_vect3_y.setGeometry(QRect(410, 340, 81, 20))
        self.fixed_vect3_y.setFont(font)
        self.fixed_row_x_lab = QLabel(dia_revpin_joint)
        self.fixed_row_x_lab.setObjectName(u"fixed_row_x_lab")
        self.fixed_row_x_lab.setGeometry(QRect(310, 280, 16, 21))
        self.fixed_row_x_lab.setFont(font)
        self.fixed_row_3_lab = QLabel(dia_revpin_joint)
        self.fixed_row_3_lab.setObjectName(u"fixed_row_3_lab")
        self.fixed_row_3_lab.setGeometry(QRect(310, 340, 16, 21))
        self.fixed_row_3_lab.setFont(font)
        self.fixed_vect2_x = QLineEdit(dia_revpin_joint)
        self.fixed_vect2_x.setObjectName(u"fixed_vect2_x")
        self.fixed_vect2_x.setGeometry(QRect(320, 310, 81, 20))
        self.fixed_vect2_x.setFont(font)
        self.fixed_vect3_x = QLineEdit(dia_revpin_joint)
        self.fixed_vect3_x.setObjectName(u"fixed_vect3_x")
        self.fixed_vect3_x.setGeometry(QRect(320, 340, 81, 20))
        self.fixed_vect3_x.setFont(font)
        self.fixed_vect1_z = QLineEdit(dia_revpin_joint)
        self.fixed_vect1_z.setObjectName(u"fixed_vect1_z")
        self.fixed_vect1_z.setGeometry(QRect(500, 280, 81, 20))
        self.fixed_vect1_z.setFont(font)
        self.fixed_vect1_y = QLineEdit(dia_revpin_joint)
        self.fixed_vect1_y.setObjectName(u"fixed_vect1_y")
        self.fixed_vect1_y.setGeometry(QRect(410, 280, 81, 20))
        self.fixed_vect1_y.setFont(font)
        self.fixed_col_y_lab = QLabel(dia_revpin_joint)
        self.fixed_col_y_lab.setObjectName(u"fixed_col_y_lab")
        self.fixed_col_y_lab.setGeometry(QRect(440, 260, 41, 21))
        self.fixed_col_y_lab.setFont(font)
        self.fixed_vect2_y = QLineEdit(dia_revpin_joint)
        self.fixed_vect2_y.setObjectName(u"fixed_vect2_y")
        self.fixed_vect2_y.setGeometry(QRect(410, 310, 81, 20))
        self.fixed_vect2_y.setFont(font)
        self.fixed_vect1_x = QLineEdit(dia_revpin_joint)
        self.fixed_vect1_x.setObjectName(u"fixed_vect1_x")
        self.fixed_vect1_x.setGeometry(QRect(320, 280, 81, 20))
        self.fixed_vect1_x.setFont(font)
        self.fixed_col_z_lab = QLabel(dia_revpin_joint)
        self.fixed_col_z_lab.setObjectName(u"fixed_col_z_lab")
        self.fixed_col_z_lab.setGeometry(QRect(530, 260, 41, 21))
        self.fixed_col_z_lab.setFont(font)
        self.fixed_OM_type_Box = QComboBox(dia_revpin_joint)
        self.fixed_OM_type_Box.addItem("")
        self.fixed_OM_type_Box.addItem("")
        self.fixed_OM_type_Box.addItem("")
        self.fixed_OM_type_Box.addItem("")
        self.fixed_OM_type_Box.addItem("")
        self.fixed_OM_type_Box.addItem("")
        self.fixed_OM_type_Box.addItem("")
        self.fixed_OM_type_Box.addItem("")
        self.fixed_OM_type_Box.setObjectName(u"fixed_OM_type_Box")
        self.fixed_OM_type_Box.setGeometry(QRect(400, 200, 101, 22))
        self.fixed_OM_type_Box.setFont(font)
        self.node1_zaxis_label = QLabel(dia_revpin_joint)
        self.node1_zaxis_label.setObjectName(u"node1_zaxis_label")
        self.node1_zaxis_label.setGeometry(QRect(100, 220, 101, 20))
        font3 = QFont()
        font3.setPointSize(9)
        self.node1_zaxis_label.setFont(font3)
        self.fixed_zaxis_label = QLabel(dia_revpin_joint)
        self.fixed_zaxis_label.setObjectName(u"fixed_zaxis_label")
        self.fixed_zaxis_label.setGeometry(QRect(410, 220, 101, 20))
        self.fixed_zaxis_label.setFont(font3)
        self.z_axies_set_x_lab = QLabel(dia_revpin_joint)
        self.z_axies_set_x_lab.setObjectName(u"z_axies_set_x_lab")
        self.z_axies_set_x_lab.setGeometry(QRect(180, 130, 81, 21))
        self.z_axies_set_x_lab.setFont(font2)
        self.z_axies_set_z_lab = QLabel(dia_revpin_joint)
        self.z_axies_set_z_lab.setObjectName(u"z_axies_set_z_lab")
        self.z_axies_set_z_lab.setGeometry(QRect(360, 130, 81, 21))
        self.z_axies_set_z_lab.setFont(font2)
        self.z_axies_set_y = QLineEdit(dia_revpin_joint)
        self.z_axies_set_y.setObjectName(u"z_axies_set_y")
        self.z_axies_set_y.setGeometry(QRect(270, 150, 81, 20))
        self.z_axies_set_y.setFont(font)
        self.Z_axis_checkBox = QCheckBox(dia_revpin_joint)
        self.Z_axis_checkBox.setObjectName(u"Z_axis_checkBox")
        self.Z_axis_checkBox.setGeometry(QRect(220, 120, 181, 16))
        self.Z_axis_checkBox.setFont(font)
        self.z_axies_set_x = QLineEdit(dia_revpin_joint)
        self.z_axies_set_x.setObjectName(u"z_axies_set_x")
        self.z_axies_set_x.setGeometry(QRect(180, 150, 81, 20))
        self.z_axies_set_x.setFont(font)
        self.z_axies_set_z = QLineEdit(dia_revpin_joint)
        self.z_axies_set_z.setObjectName(u"z_axies_set_z")
        self.z_axies_set_z.setGeometry(QRect(360, 150, 81, 20))
        self.z_axies_set_z.setFont(font)
        self.z_axies_set_y_lab = QLabel(dia_revpin_joint)
        self.z_axies_set_y_lab.setObjectName(u"z_axies_set_y_lab")
        self.z_axies_set_y_lab.setGeometry(QRect(270, 130, 81, 21))
        self.z_axies_set_y_lab.setFont(font2)
        self.frame = QFrame(dia_revpin_joint)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(5, 180, 291, 191))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Plain)
        self.node1_OM_type_label = QLabel(self.frame)
        self.node1_OM_type_label.setObjectName(u"node1_OM_type_label")
        self.node1_OM_type_label.setGeometry(QRect(70, 0, 151, 20))
        self.node1_OM_type_label.setFont(font1)
        self.frame_2 = QFrame(dia_revpin_joint)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(305, 180, 291, 191))
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.fixed_OM_type_label = QLabel(self.frame_2)
        self.fixed_OM_type_label.setObjectName(u"fixed_OM_type_label")
        self.fixed_OM_type_label.setGeometry(QRect(60, 0, 151, 20))
        self.fixed_OM_type_label.setFont(font1)
        self.node1_OM_input_lab = QLabel(dia_revpin_joint)
        self.node1_OM_input_lab.setObjectName(u"node1_OM_input_lab")
        self.node1_OM_input_lab.setGeometry(QRect(90, 240, 141, 21))
        self.node1_OM_input_lab.setFont(font1)
        self.fifed_OM_input_lab = QLabel(dia_revpin_joint)
        self.fifed_OM_input_lab.setObjectName(u"fifed_OM_input_lab")
        self.fifed_OM_input_lab.setGeometry(QRect(390, 240, 141, 21))
        self.fifed_OM_input_lab.setFont(font1)
        self.frame_2.raise_()
        self.frame.raise_()
        self.buttonBox.raise_()
        self.node_1_Box.raise_()
        self.node_1_label.raise_()
        self.node1_pos_x.raise_()
        self.node1_posx_lab.raise_()
        self.node1_pos_y.raise_()
        self.node1_posy_lab.raise_()
        self.node1_pos_z.raise_()
        self.node1_posz_lab.raise_()
        self.node1_pos_label.raise_()
        self.fixed_pos_y.raise_()
        self.fixed_posx_lab.raise_()
        self.fixed_pos_label.raise_()
        self.fixed_posz_lab.raise_()
        self.fixed_pos_z.raise_()
        self.fixed_posy_lab.raise_()
        self.fixed_pos_x.raise_()
        self.node1_OM_type_Box.raise_()
        self.node1_vect1_x.raise_()
        self.node1_col_x_lab.raise_()
        self.node1_col_y_lab.raise_()
        self.node1_vect1_y.raise_()
        self.node1_vect1_z.raise_()
        self.node1_col_z_lab.raise_()
        self.node1_vect2_z.raise_()
        self.node1_vect2_y.raise_()
        self.node1_vect2_x.raise_()
        self.node1_vect3_z.raise_()
        self.node1_vect3_x.raise_()
        self.node1_vect3_y.raise_()
        self.node1_row_x_lab.raise_()
        self.node1_row_2_lab.raise_()
        self.node1_row_3_lab.raise_()
        self.fixed_row_2_lab.raise_()
        self.fixed_col_x_lab.raise_()
        self.fixed_vect2_z.raise_()
        self.fixed_vect3_z.raise_()
        self.fixed_vect3_y.raise_()
        self.fixed_row_x_lab.raise_()
        self.fixed_row_3_lab.raise_()
        self.fixed_vect2_x.raise_()
        self.fixed_vect3_x.raise_()
        self.fixed_vect1_z.raise_()
        self.fixed_vect1_y.raise_()
        self.fixed_col_y_lab.raise_()
        self.fixed_vect2_y.raise_()
        self.fixed_vect1_x.raise_()
        self.fixed_col_z_lab.raise_()
        self.fixed_OM_type_Box.raise_()
        self.node1_zaxis_label.raise_()
        self.fixed_zaxis_label.raise_()
        self.z_axies_set_x_lab.raise_()
        self.z_axies_set_z_lab.raise_()
        self.z_axies_set_y.raise_()
        self.Z_axis_checkBox.raise_()
        self.z_axies_set_x.raise_()
        self.z_axies_set_z.raise_()
        self.z_axies_set_y_lab.raise_()
        self.node1_OM_input_lab.raise_()
        self.fifed_OM_input_lab.raise_()

        self.retranslateUi(dia_revpin_joint)
        self.buttonBox.accepted.connect(dia_revpin_joint.accept)
        self.buttonBox.rejected.connect(dia_revpin_joint.reject)

        QMetaObject.connectSlotsByName(dia_revpin_joint)
    # setupUi

    def retranslateUi(self, dia_revpin_joint):
        dia_revpin_joint.setWindowTitle(QCoreApplication.translate("dia_revpin_joint", u"revlute pin joint", None))
        self.node_1_label.setText(QCoreApplication.translate("dia_revpin_joint", u"node", None))
        self.node1_posx_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"node pos. x", None))
        self.node1_posy_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"node pos. y", None))
        self.node1_posz_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"node pos. z", None))
        self.node1_pos_label.setText(QCoreApplication.translate("dia_revpin_joint", u"position relative to node", None))
        self.fixed_posx_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"fixed pos. x", None))
        self.fixed_pos_label.setText(QCoreApplication.translate("dia_revpin_joint", u"absolute position fixed", None))
        self.fixed_posz_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"fixed pos. z", None))
        self.fixed_posy_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"fixed pos. y", None))
        self.node1_OM_type_Box.setItemText(0, QCoreApplication.translate("dia_revpin_joint", u"xy", None))
        self.node1_OM_type_Box.setItemText(1, QCoreApplication.translate("dia_revpin_joint", u"xz", None))
        self.node1_OM_type_Box.setItemText(2, QCoreApplication.translate("dia_revpin_joint", u"yz", None))
        self.node1_OM_type_Box.setItemText(3, QCoreApplication.translate("dia_revpin_joint", u"matr", None))
        self.node1_OM_type_Box.setItemText(4, QCoreApplication.translate("dia_revpin_joint", u"euler123", None))
        self.node1_OM_type_Box.setItemText(5, QCoreApplication.translate("dia_revpin_joint", u"euler313", None))
        self.node1_OM_type_Box.setItemText(6, QCoreApplication.translate("dia_revpin_joint", u"euler321", None))
        self.node1_OM_type_Box.setItemText(7, QCoreApplication.translate("dia_revpin_joint", u"vector", None))

        self.node1_col_x_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"X", None))
        self.node1_col_y_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"Y", None))
        self.node1_col_z_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"Z", None))
        self.node1_row_x_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"1", None))
        self.node1_row_2_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"2", None))
        self.node1_row_3_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"3", None))
        self.fixed_row_2_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"2", None))
        self.fixed_col_x_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"X", None))
        self.fixed_row_x_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"1", None))
        self.fixed_row_3_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"3", None))
        self.fixed_col_y_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"Y", None))
        self.fixed_col_z_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"Z", None))
        self.fixed_OM_type_Box.setItemText(0, QCoreApplication.translate("dia_revpin_joint", u"xy", None))
        self.fixed_OM_type_Box.setItemText(1, QCoreApplication.translate("dia_revpin_joint", u"xz", None))
        self.fixed_OM_type_Box.setItemText(2, QCoreApplication.translate("dia_revpin_joint", u"yz", None))
        self.fixed_OM_type_Box.setItemText(3, QCoreApplication.translate("dia_revpin_joint", u"matr", None))
        self.fixed_OM_type_Box.setItemText(4, QCoreApplication.translate("dia_revpin_joint", u"euler123", None))
        self.fixed_OM_type_Box.setItemText(5, QCoreApplication.translate("dia_revpin_joint", u"euler313", None))
        self.fixed_OM_type_Box.setItemText(6, QCoreApplication.translate("dia_revpin_joint", u"euler321", None))
        self.fixed_OM_type_Box.setItemText(7, QCoreApplication.translate("dia_revpin_joint", u"vector", None))

        self.node1_zaxis_label.setText(QCoreApplication.translate("dia_revpin_joint", u"Z axix is axis of rotation", None))
        self.fixed_zaxis_label.setText(QCoreApplication.translate("dia_revpin_joint", u"Z axis is axis of rotation", None))
        self.z_axies_set_x_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"z_axis set x", None))
        self.z_axies_set_z_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"z_axis set z", None))
        self.Z_axis_checkBox.setText(QCoreApplication.translate("dia_revpin_joint", u"set revolute axis on FreeCad model", None))
        self.z_axies_set_y_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"z_axis set y", None))
        self.node1_OM_type_label.setText(QCoreApplication.translate("dia_revpin_joint", u"node orientation matrix type", None))
        self.fixed_OM_type_label.setText(QCoreApplication.translate("dia_revpin_joint", u"fixed orientation matrix type", None))
        self.node1_OM_input_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"orientation matrix input", None))
        self.fifed_OM_input_lab.setText(QCoreApplication.translate("dia_revpin_joint", u"orientation matrix input", None))
    # retranslateUi

