# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dia_launcher.ui',
# licensing of 'dia_launcher.ui' applies.
#
# Created: Wed Jul 22 22:54:50 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dia_launcher(object):
    def setupUi(self, dia_launcher):
        dia_launcher.setObjectName("dia_launcher")
        dia_launcher.resize(317, 324)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dia_launcher.sizePolicy().hasHeightForWidth())
        dia_launcher.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(dia_launcher)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(dia_launcher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.active_solver = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_solver.sizePolicy().hasHeightForWidth())
        self.active_solver.setSizePolicy(sizePolicy)
        self.active_solver.setObjectName("active_solver")
        self.horizontalLayout.addWidget(self.active_solver)
        self.useWSL = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useWSL.sizePolicy().hasHeightForWidth())
        self.useWSL.setSizePolicy(sizePolicy)
        self.useWSL.setMinimumSize(QtCore.QSize(30, 0))
        self.useWSL.setObjectName("useWSL")
        self.horizontalLayout.addWidget(self.useWSL)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(dia_launcher)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.out_filename = QtWidgets.QLineEdit(self.groupBox_2)
        self.out_filename.setObjectName("out_filename")
        self.gridLayout.addWidget(self.out_filename, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.out_location = QtWidgets.QLineEdit(self.groupBox_2)
        self.out_location.setObjectName("out_location")
        self.gridLayout.addWidget(self.out_location, 1, 1, 1, 1)
        self.fp_outfile = QtWidgets.QPushButton(self.groupBox_2)
        self.fp_outfile.setObjectName("fp_outfile")
        self.gridLayout.addWidget(self.fp_outfile, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.editIF = QtWidgets.QPushButton(dia_launcher)
        self.editIF.setObjectName("editIF")
        self.gridLayout_2.addWidget(self.editIF, 0, 2, 1, 2)
        self.writeIF = QtWidgets.QPushButton(dia_launcher)
        self.writeIF.setObjectName("writeIF")
        self.gridLayout_2.addWidget(self.writeIF, 0, 0, 1, 2)
        self.runSim = QtWidgets.QPushButton(dia_launcher)
        self.runSim.setMinimumSize(QtCore.QSize(291, 25))
        self.runSim.setObjectName("runSim")
        self.gridLayout_2.addWidget(self.runSim, 1, 0, 1, 4)
        self.stopSim = QtWidgets.QPushButton(dia_launcher)
        self.stopSim.setMinimumSize(QtCore.QSize(291, 25))
        self.stopSim.setObjectName("stopSim")
        self.gridLayout_2.addWidget(self.stopSim, 2, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 3, 1, 1)
        self.viewStatus = QtWidgets.QPushButton(dia_launcher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewStatus.sizePolicy().hasHeightForWidth())
        self.viewStatus.setSizePolicy(sizePolicy)
        self.viewStatus.setMinimumSize(QtCore.QSize(101, 25))
        self.viewStatus.setObjectName("viewStatus")
        self.gridLayout_2.addWidget(self.viewStatus, 3, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_2)

        self.retranslateUi(dia_launcher)
        QtCore.QMetaObject.connectSlotsByName(dia_launcher)

    def retranslateUi(self, dia_launcher):
        dia_launcher.setWindowTitle(QtWidgets.QApplication.translate("dia_launcher", "Dialog", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("dia_launcher", "Solver Settings:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("dia_launcher", "Actual Solver:", None, -1))
        self.useWSL.setText(QtWidgets.QApplication.translate("dia_launcher", "use WSL", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("dia_launcher", "Output File:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("dia_launcher", "Name", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("dia_launcher", "Path", None, -1))
        self.fp_outfile.setText(QtWidgets.QApplication.translate("dia_launcher", "Browse...", None, -1))
        self.editIF.setText(QtWidgets.QApplication.translate("dia_launcher", "Edit Input File", None, -1))
        self.writeIF.setText(QtWidgets.QApplication.translate("dia_launcher", "Write Input File", None, -1))
        self.runSim.setText(QtWidgets.QApplication.translate("dia_launcher", "Run Simulation", None, -1))
        self.stopSim.setText(QtWidgets.QApplication.translate("dia_launcher", "Stop Simulation", None, -1))
        self.viewStatus.setText(QtWidgets.QApplication.translate("dia_launcher", "View status", None, -1))

